export const SIGNIN_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const SIGNIN_FAILURE = 'FETCH-AUTH_FAILURE';
export const LOGOUT_SUCCESS = 'FETCH_LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'FETCH_LOGOUT_FAILURE';
